export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';

export const EMPLOYEE_DETAIL_START = 'EMPLOYEE_DETAIL_START';
export const EMPLOYEE_DETAIL_SUCCESS = 'EMPLOYEE_DETAIL_SUCCESS';
export const EMPLOYEE_DETAIL_FAIL = 'EMPLOYEE_DETAIL_FAIL';